lr: 1e-4
lr_decay_step: 50

log_train_metrics: True
log_train_visual: True
log_visual_every_n_epoch: 1

trainer:
    max_epochs: 5000 #5000
    log_every_n_steps: 1
    check_val_every_n_epoch: 50 #10
    fast_dev_run: False
    limit_train_batches: 1.0
    limit_val_batches: 1.0
#    resume_from_checkpoint: